In [0]:
import os
import numpy as np

In [0]:
! wget -q https://cdn.glitch.com/c16f71ef-e58b-4291-89f3-62975c2ebc7f%2Fout12345.zip?v=1589899041000 -O out12345.zip
! wget -q https://cdn.glitch.com/c16f71ef-e58b-4291-89f3-62975c2ebc7f%2Fsource.zip?v=1589899049985 -O source.zip
! unzip -o out12345.zip
! unzip -o source.zip

Archive:  out12345.zip
   creating: out12345/
   creating: out12345/vung1/
  inflating: out12345/vung1/bacGiang_1589607623485.txt  
 extracting: out12345/vung1/bacGiang_1589607623485_label.txt  
  inflating: out12345/vung1/bacGiang_1589607623545.txt  
 extracting: out12345/vung1/bacGiang_1589607623545_label.txt  
  inflating: out12345/vung1/bacGiang_1589607623550.txt  
 extracting: out12345/vung1/bacGiang_1589607623550_label.txt  
  inflating: out12345/vung1/bacGiang_1589607623564.txt  
 extracting: out12345/vung1/bacGiang_1589607623564_label.txt  
  inflating: out12345/vung1/bacGiang_1589607623566.txt  
 extracting: out12345/vung1/bacGiang_1589607623566_label.txt  
  inflating: out12345/vung1/bacGiang_1589607623573.txt  
 extracting: out12345/vung1/bacGiang_1589607623573_label.txt  
  inflating: out12345/vung1/bacGiang_1589607623582.txt  
 extracting: out12345/vung1/bacGiang_1589607623582_label.txt  
  inflating: out12345/vung1/bacGiang_1589607623587.txt  
 extracting: out12345/vung1/

In [0]:
containing_folder = './out12345'

In [0]:
hiring_jobs = []
hiring_areas = []

for label_folder in os.listdir(containing_folder):
    temp_area = []
    label_path = containing_folder + '/' + label_folder + '/'
    for file in os.listdir(label_path):
        if '_label' in file:
            with open(label_path + file, 'r') as label_file:
                label = label_file.read().replace('\n', '')
                if label != '':
                    hiring_jobs.append(label)
                    temp_area.append(file.split('_')[0])
    hiring_areas.append(temp_area)
hiring_jobs = np.array(hiring_jobs)
hiring_areas = np.array(hiring_areas)

In [0]:
ujob = np.unique(hiring_jobs)
for j in ujob:
    print(j)

ban_hang
bao_ve
bep
cong_nhan
giao_vien
giup_viec
huong_dan_vien_du_lich
ke_toan
ky_su
lai_xe
nhan_vien
pha_che
phien_dich
phuc_vu
quan_ly
sale_online
tho_lap_may
tho_xay
thoi_vu
tro_ly
y_te


In [0]:
label_dict = {}
for idx, j in enumerate(ujob):
    label_dict[j] = idx
print(label_dict)


{'ban_hang': 0, 'bao_ve': 1, 'bep': 2, 'cong_nhan': 3, 'giao_vien': 4, 'giup_viec': 5, 'huong_dan_vien_du_lich': 6, 'ke_toan': 7, 'ky_su': 8, 'lai_xe': 9, 'nhan_vien': 10, 'pha_che': 11, 'phien_dich': 12, 'phuc_vu': 13, 'quan_ly': 14, 'sale_online': 15, 'tho_lap_may': 16, 'tho_xay': 17, 'thoi_vu': 18, 'tro_ly': 19, 'y_te': 20}


In [0]:
finding_job_containing_folder = './source/'

In [0]:
finding_jobs = []
finding_areas = []

for finding_label in os.listdir(finding_job_containing_folder):
  if '_label' in finding_label:
    with open(finding_job_containing_folder + finding_label, 'r') as label_file:
      labels = label_file.read().replace(' ', '')
      labels = labels.split('\n')
      job = [0] * (len(label_dict) + 1)
      for l in labels[:-1]:
        job[get_hot_encode(l)] = 1
      try:
        job[-1] = int(labels[-1])
        # print(job)
        # break
        finding_jobs.append(job)
      except:
        pass
finding_jobs = np.array(finding_jobs)
# finding_areas = np.array(finding_areas)
print(finding_jobs)

[[ 1  0  1 ...  0  0 50]
 [ 1  0  0 ...  0  0 50]
 [ 1  1  1 ...  0  0 20]
 ...
 [ 1  0  1 ...  0  0 19]
 [ 0  1  0 ...  0  0 19]
 [ 1  1  1 ...  1  0 20]]


In [0]:
def get_hot_encode(job):
    return label_dict[job]

def one_hot_encode(jobs):
    one_hot_array = np.zeros((len(jobs), len(ujob)+ 1), np.uint8)
    
    for idx, j in enumerate(jobs):
        one_hot_array[idx][j] = 1
        
    return one_hot_array

In [0]:
hiring_jobs = np.array([get_hot_encode(j) for j in hiring_jobs])
print(hiring_jobs)


[18  9 10 ...  7  3  1]


In [0]:
hiring_jobs_onehot = np.zeros((len(hiring_jobs), max(hiring_jobs) + 2), np.uint8)
for h, o in zip(hiring_jobs, hiring_jobs_onehot):
  o[h] = 1
print(hiring_jobs_onehot)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


In [0]:
finding_jobs

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]])

In [0]:
X_data = []
y_true = []

for hiring in hiring_jobs_onehot:
    amax = np.argmax(hiring)
    for finding in finding_jobs:
        #Check this employee is good to hire and generate training label
        if finding[amax] == 1:
            y_true.append(1)
        else: 
            y_true.append(0)
        #Generate input data
        temp_index = finding - hiring
        # print(finding)
        # print(hiring)
        X_data.append(temp_index)
        # break
    # break
            
X_data = np.array(X_data)
y_true = np.array(y_true)

print(X_data.shape)
print(y_true.shape)
print(X_data[:5])

(268150, 22)
(268150,)
[[ 1  0  1  0  0  1  0  1  0  0  1  0  0  0  1  1  0  0  0  0  0 50]
 [ 1  0  0  0  0  1  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0 50]
 [ 1  1  1  1  0  0  0  0  0  1  1  1  0  1  0  1  1  1 -1  0  0 20]
 [ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0 22]
 [ 1  1  1  1  0  1  0  0  0  1  1  1  0  1  1  0  1  1 -1  0  0 24]]


In [0]:
X_data[0]

array([ 1,  0,  1,  0,  0,  1,  0,  1,  0,  0,  1,  0,  0,  0,  1,  1,  0,
        0,  0,  0,  0, 50])

In [0]:
import keras.backend as K
from keras.optimizers import Adam
from keras.losses import mean_squared_error
from keras.layers import Dense, Input, Dropout
from keras.models import Model

Using TensorFlow backend.


In [0]:
def build_recommender_model(input_shape = 22):
    inpt = Input((input_shape, ))
    
    dns1 = Dense(32, activation='relu')(inpt)
    dns1 = Dense(64, activation='relu')(dns1)
    dns1 = Dropout(0.5)(dns1)
    dns1 = Dense(16, activation='relu')(dns1)
    dns1 = Dense(1, activation='sigmoid')(dns1)
    
    return Model(inpt, dns1)

In [0]:
train_model = build_recommender_model()

In [0]:
train_model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 22)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 32)                736       
_________________________________________________________________
dense_2 (Dense)              (None, 64)                2112      
_________________________________________________________________
dropout_1 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 16)                1040      
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 17        
Total params: 3,905
Trainable params: 3,905
Non-trainable params: 0
_________________________________________________________

In [0]:
train_model.compile(Adam(1e-4), loss='binary_crossentropy', metrics=['accuracy'])

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_data, y_true)

In [0]:
train_model.fit(X_train, y_train, batch_size = 16, epochs = 100, validation_data=[X_test, y_test])

Train on 201112 samples, validate on 67038 samples
Epoch 1/100
201112/201112 [==============================] - 47s 235us/step - loss: 0.5546 - accuracy: 0.7079 - val_loss: 0.3866 - val_accuracy: 0.8287
Epoch 2/100
201112/201112 [==============================] - 46s 227us/step - loss: 0.3330 - accuracy: 0.8535 - val_loss: 0.2126 - val_accuracy: 0.9299
Epoch 3/100
201112/201112 [==============================] - 46s 229us/step - loss: 0.2210 - accuracy: 0.9136 - val_loss: 0.1426 - val_accuracy: 0.9534
Epoch 4/100
201112/201112 [==============================] - 46s 228us/step - loss: 0.1687 - accuracy: 0.9379 - val_loss: 0.1059 - val_accuracy: 0.9674
Epoch 5/100
201112/201112 [==============================] - 47s 232us/step - loss: 0.1379 - accuracy: 0.9511 - val_loss: 0.0873 - val_accuracy: 0.9737
Epoch 6/100
201112/201112 [==============================] - 46s 229us/step - loss: 0.1189 - accuracy: 0.9597 - val_loss: 0.0767 - val_accuracy: 0.9820
Epoch 7/100
201112/201112 [==========

KeyboardInterrupt: ignored

In [0]:
train_model.save('./recommender.h5')